services:
  flask-model:
    container_name: backend_flask_model
    image: backend_flask_model
    build: ../backend
    ports:
      - "5000:5000"
  dash-app:
    container_name: frontend_dash_app
    image: frontend_dash_app
    volumes:
      - imageCurrShown:/app/src/assets/imageCurrShown
    build:
      context: .
      dockerfile: dash_dockerfile.txt
    ports:
      - "8050:8050"
  result-gen:
    container_name: frontend_result_gen
    image: frontend_result_gen
    volumes:
      - imageCurrShown:/app/assets/imageCurrShown
      - imageToBeUpdated:/app/assets/imageToBeUpdated
    build: ./src/result_generator
    depends_on:
      - "redis-cache"
      - "flask-model"
  redis-cache:
    container_name: frontend_redis_cache
    image: redis
    ports:
      - "6379:6379"

volumes:
  imageCurrShown:
  imageToBeUpdated:

