services:
  flask_model:
    container_name: backend
    build: ../backend
    ports:
      - "5000:5000"
  dash_app:
    container_name: frontend
    build:
      context: .
      dockerfile: dash_dockerfile.txt
    ports:
      - "8050:8050"
